'use client';
import {useEffect,useState} from 'react';
import dynamic from 'next/dynamic';
import Image from 'next/image';
import OrangeSequence from './orange-sequence';
import {ArrowUpRight,ArrowDown,ArrowRight,ShoppingBag,Plus,Minus,X,Menu,Leaf,Sun,Package,UserRound} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Sheet,SheetContent,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {initialProducts,imagePath,sitePath,logo,money,type Product} from '@/lib/catalog';
const ProductScene=dynamic(()=>import('./product-scene'),{ssr:false,loading:()=> <div className="scene-loading"><span/></div>});
export default function Storefront({lang}:{lang:'it'|'en'}){
 const en=lang==='en',t=(it:string,english:string)=>en?english:it;
 const [category,setCategory]=useState('Tutti');const [selected,setSelected]=useState<Product|null>(null);const [cartOpen,setCartOpen]=useState(false);const [menu,setMenu]=useState(false);const [cart,setCart]=useState<{product:Product;qty:number}[]>([]);const [quantity,setQuantity]=useState(1);const [checkout,setCheckout]=useState(false);
 const count=cart.reduce((n,i)=>n+i.qty,0),total=cart.reduce((n,i)=>n+i.qty*i.product.price,0);
 useEffect(()=>{document.documentElement.lang=lang;let destroy=()=>{};let closed=false;
  Promise.all([import('gsap'),import('gsap/ScrollTrigger')]).then(([{gsap},{ScrollTrigger}])=>{if(closed)return;gsap.registerPlugin(ScrollTrigger);const mm=gsap.matchMedia();mm.add('(prefers-reduced-motion: no-preference)',()=>{
   gsap.timeline({scrollTrigger:{trigger:'#citrus',start:'top top',end:'bottom bottom',scrub:.6}}).to('.citrus-intro',{autoAlpha:0,y:-35,duration:.2},.23).fromTo('.citrus-outro',{autoAlpha:0,y:35},{autoAlpha:1,y:0,duration:.2},.43).to('.hero-scroll',{opacity:0,duration:.1},.1).to('.chapter-progress',{scaleX:1,duration:1,ease:'none'},0);
   gsap.fromTo('.oil-copy',{y:50,opacity:.4},{y:0,opacity:1,scrollTrigger:{trigger:'#oil',start:'top 70%',end:'top 10%',scrub:1}});
   gsap.utils.toArray<HTMLElement>('.reveal').forEach(el=>{gsap.fromTo(el,{y:24,opacity:.45},{y:0,opacity:1,duration:.8,scrollTrigger:{trigger:el,start:'top 92%',once:true}});});
  });destroy=()=>mm.revert();});return()=>{closed=true;destroy();};
 },[lang]);
 const add=(p:Product,q=1)=>{setCart(old=>{const item=old.find(i=>i.product.id===p.id);return item?old.map(i=>i.product.id===p.id?{...i,qty:i.qty+q}:i):[...old,{product:p,qty:q}];});setSelected(null);setCheckout(false);setCartOpen(true);};
 const changeQty=(id:string,n:number)=>setCart(old=>old.map(i=>i.product.id===id?{...i,qty:i.qty+n}:i).filter(i=>i.qty>0));
 function goCategory(c:string){setCategory(c);document.getElementById('products')?.scrollIntoView({behavior:'smooth'});}
 const cats=['Tutti','Olio EVO','Oli aromatizzati','Agrumi','Specialità'];const catEn=['All products','Extra virgin olive oil','Flavoured oils','Citrus','Specialities'];
 const shown=initialProducts.filter(p=>category==='Tutti'||p.category===category);
 return <div className="storefront">
  <a href="#main" className="skip-link">{t('Vai al contenuto','Skip to content')}</a>
  <div className="announcement"><span>{process.env.NEXT_PUBLIC_DEMO_BANNER==='1'?t('DEMO DI DESIGN · Acquisti non disponibili','DESIGN DEMO · Purchasing unavailable'):t('Dalla nostra terra. Alla tua tavola.','From our land. To your table.')}</span><span>SCIACCA, SICILIA · 37°30′ N 13°05′ E</span></div>
  <header className="site-header">
   <a className="brand" href={sitePath(en?'/en/':'/it/')} aria-label="Tenute Santangelo home"><Image unoptimized src={imagePath(logo)} width={56} height={56} alt=""/><span>TENUTE<br/><strong>SANTANGELO</strong><small>SICILIA</small></span></a>
   <nav className="desktop-nav" aria-label={t('Navigazione principale','Main navigation')}><a href="#products">{t('La nostra dispensa','Our pantry')}</a><a href="#oil">{t('L’olio','Olive oil')}</a><a href="#land">{t('La tenuta','Our land')}</a></nav>
   <div className="header-actions"><a className="language" href={sitePath(en?'/it/':'/en/')} aria-label={en?'Passa a italiano':'Switch to English'}><span>{en?'🇬🇧':'🇮🇹'}</span>{en?'EN':'IT'}<span className="chevron">⌄</span></a><a href={sitePath('/admin/')} className="icon-button account-link" aria-label={t('Area amministrativa demo','Demo administration')}><UserRound size={19}/></a><button className="bag-button" onClick={()=>setCartOpen(true)} aria-label={`${t('Apri carrello','Open bag')} (${count})`}><ShoppingBag size={20}/><span>{count}</span></button><button className="icon-button mobile-menu" onClick={()=>setMenu(true)} aria-label={t('Apri menu','Open menu')}><Menu/></button></div>
  </header>
  <main id="main">
   <section className="citrus-section" id="citrus">
    <div className="citrus-sticky">
     <div className="hero-grain"/>
     <div className="hero-orbit" aria-hidden="true"/>
     <div className="hero-copy citrus-intro"><p className="eyebrow"><span className="tiny-sun">✳</span> {t('COLTIVIAMO UN PEZZO DI SICILIA','A LITTLE PIECE OF SICILY')}</p><h1>{t('Il sole,','Sunshine,')}<br/><em>{t('a casa tua.','at your door.')}</em></h1><p className="hero-description">{t('Ci sono sapori che ti portano lontano. E altri che ti fanno sentire a casa. I nostri fanno entrambe le cose.','Some flavours take you places. Others make you feel at home. Ours do both.')}</p><a className="pill-button dark" href="#products">{t('Assapora la Sicilia','Taste Sicily')}<ArrowUpRight size={19}/></a></div>
     <div className="hero-copy citrus-outro"><p className="eyebrow">{t('APRI. RESPIRA. ASSAPORA.','OPEN. BREATHE. TASTE.')}</p><h2>{t('Dentro,','Inside,')}<br/><em>{t('tutta Sicilia.','all of Sicily.')}</em></h2><p className="hero-description">{t('Il profumo della buccia. Il colore del sole. La meraviglia delle cose semplici, spicchio dopo spicchio.','The scent of the peel. The colour of sunshine. The wonder of simple things, segment after segment.')}</p><button className="pill-button dark" onClick={()=>goCategory('Agrumi')}>{t('Scopri gli agrumi','Discover our citrus')}<ArrowUpRight size={19}/></button></div>
     <div className="hero-visual hero-visual--sequence"><OrangeSequence sectionId="citrus" lang={lang}/><span className="fruit-caption">CITRUS SINENSIS<br/><b>{t('L’essenza del Mediterraneo','The essence of the Mediterranean')}</b></span></div>
     <div className="hero-scroll"><span>{t('LA NATURA HA IL SUO RITMO. SEGUI IL TUO.','NATURE HAS ITS OWN RHYTHM. FIND YOURS.')}</span><span className="scroll-round"><ArrowDown size={18}/></span><small>{t('Scorri e scopri','Scroll to discover')}</small></div>
     <div className="chapter-label"><span>01 / 03</span><span>{t('IL SOLE','SUNSHINE')}</span></div><div className="chapter-progress"/>
    </div>
   </section>
   <div className="values-strip"><span><Sun/>{t('L’anima della Sicilia','The soul of Sicily')}</span><span><Leaf/>{t('La passione di famiglia','A family’s passion')}</span><span><Package/>{t('Dalla terra alla tavola','From the land to your table')}</span></div>
   <section id="oil" className="oil-section"><div className="oil-sticky"><div className="oil-watermark" aria-hidden="true">EXTRA<br/>VERGINE</div><div className="oil-visual"><ProductScene kind="oil" sectionId="oil" lang={lang}/></div><div className="oil-copy"><p className="eyebrow">02 / {t('IL NOSTRO ORO VERDE','OUR LIQUID GOLD')}</p><h2>{t('Un filo d’olio.','A drizzle of oil.')}<br/><em>{t('Un mondo','A world')}<br/>{t('dentro.','within.')}</em></h2><p>{t('Dagli ulivi della nostra terra nasce il gesto più semplice della cucina siciliana. Bastano poche gocce per ritrovarsi a casa.','From the olive trees of our land comes the simplest gesture in Sicilian cooking. Just a few drops to feel at home.')}</p><button className="pill-button gold" onClick={()=>goCategory('Olio EVO')}>{t('Scopri il nostro olio','Discover our olive oil')}<ArrowUpRight size={19}/></button><div className="oil-note"><span>OLEA EUROPAEA</span><span>SCIACCA · SICILIA</span></div></div></div></section>
   <section className="products-section" id="products"><div className="section-top reveal"><div><p className="eyebrow">{t('LE COSE BUONE, QUELLE VERE','GOOD THINGS, GROWN WITH CARE')}</p><h2>{t('La nostra','Our')} <em>{t('dispensa.','pantry.')}</em></h2></div><p>{t('Una selezione di casa nostra.\nScegli cosa portare sulla tua tavola.','A selection from our home.\nChoose what to bring to your table.')}</p></div><div className="catalog-tools"><div className="category-filters" aria-label={t('Filtra prodotti','Filter products')}>{cats.map((c,i)=><button key={c} className={category===c?'active':''} onClick={()=>setCategory(c)}>{en?catEn[i]:c}</button>)}</div><span className="catalog-count">{shown.length} {t('prodotti','products')}</span></div><div className="product-grid">{shown.map((p,i)=><article className="product-card" key={p.id}><button className="product-image" onClick={()=>{setSelected(p);setQuantity(1);}} aria-label={`${t('Scopri','Discover')} ${en?p.nameEn:p.name}`}><span className="product-category">{en?catEn[cats.indexOf(p.category)]:p.category}</span><Image unoptimized src={imagePath(p.image)} width={500} height={500} alt={en?p.nameEn:p.name} loading="lazy"/><span className="product-open"><ArrowUpRight size={22}/></span></button><div className="product-info"><div><h3><button onClick={()=>{setSelected(p);setQuantity(1);}}>{en?p.nameEn:p.name}</button></h3><span>{p.format}</span></div><strong>{money(p.price,lang)}</strong></div></article>)}</div><p className="demo-prices">{t('Anteprima del catalogo · Prezzi e disponibilità dimostrativi.','Catalogue preview · Illustrative prices and availability.')}</p></section>
   <section className="land-section" id="land"><div className="land-photo"><Image unoptimized src={imagePath('ulivo-in-fiore-147571.jpg')} alt={t('Rami di ulivo in fiore','Olive branches in bloom')} width={900} height={1200}/><span className="photo-label">37°30′ N · 13°05′ E<br/>SCIACCA, SICILIA</span></div><div className="land-copy reveal"><p className="eyebrow">03 / {t('LE NOSTRE RADICI','OUR ROOTS')}</p><h2>{t('Prima di un','Before a')}<br/>{t('prodotto,','product,')}<br/><em>{t('una storia.','a story.')}</em></h2><p>{t('Tra gli ulivi, gli agrumeti e il vento salato di Sciacca, la nostra famiglia si prende cura di un’eredità semplice: fare le cose per bene.','Among the olive groves, citrus trees and salty breeze of Sciacca, our family tends to a simple legacy: doing things with care.')}</p><p>{t('Ogni raccolto è un nuovo capitolo. Ogni prodotto, un piccolo pezzo della nostra Sicilia da condividere.','Every harvest is a new chapter. Every product, a little piece of our Sicily to share.')}</p><div className="signature">La famiglia Santangelo</div><a className="text-link" href="mailto:info@tenutesantangelo.it">{t('Parliamone insieme','Get in touch')}<ArrowUpRight size={18}/></a></div></section>
   <section className="closing-section"><Image unoptimized src={imagePath('olive-raccolte-147561.jpg')} alt={t('Olive raccolte','Freshly harvested olives')} width={1200} height={1600}/><div><p className="eyebrow">TENUTE SANTANGELO · SICILIA</p><h2>{t('Le cose buone','Good things')}<br/><em>{t('si condividono.','are for sharing.')}</em></h2><a href="#products" className="pill-button light">{t('Scegli il tuo pezzo di Sicilia','Choose your piece of Sicily')}<ArrowUpRight size={20}/></a></div></section>
  </main>
  <footer><div className="footer-main"><a className="footer-brand" href="#">TENUTE<br/>SANTANGELO<small>SICILIA</small></a><div><p>{t('LA NOSTRA TERRA','OUR LAND')}</p><span>Via Ferraro 2, Sciacca (AG)</span><span>92019 · Sicilia, Italia</span></div><div><p>{t('RESTIAMO IN CONTATTO','KEEP IN TOUCH')}</p><a href="mailto:info@tenutesantangelo.it">info@tenutesantangelo.it</a><a href="tel:+393467169584">+39 346 7169584</a></div><div><p>{t('ESPLORA','EXPLORE')}</p><a href="#products">{t('La dispensa','The pantry')}</a><a href={sitePath('/admin/')}>{t('Amministrazione · demo','Administration · demo')}</a></div></div><div className="footer-bottom"><span>© 2026 Tenute Santangelo · P.IVA 02101940845</span><span>{t('Fatto di terra, sole e famiglia.','Made of land, sunshine and family.')}</span></div></footer>
  <Dialog open={!!selected} onOpenChange={v=>{if(!v)setSelected(null);}}><DialogContent className="product-dialog">{selected&&<><div className="dialog-product-image"><Image unoptimized src={imagePath(selected.image)} width={600} height={600} alt={en?selected.nameEn:selected.name}/></div><div className="dialog-product-copy"><p className="eyebrow">TENUTE SANTANGELO</p><DialogTitle className="dialog-heading">{en?selected.nameEn:selected.name}</DialogTitle><DialogDescription className="dialog-description">{en?selected.descriptionEn:selected.description}</DialogDescription><span className="format-label">{selected.format}</span><strong className="detail-price">{money(selected.price,lang)}</strong><div className="quantity"><button onClick={()=>setQuantity(Math.max(1,quantity-1))} aria-label={t('Riduci quantità','Decrease quantity')}><Minus size={16}/></button><span>{quantity}</span><button onClick={()=>setQuantity(Math.min(99,quantity+1))} aria-label={t('Aumenta quantità','Increase quantity')}><Plus size={16}/></button></div><button className="pill-button dark" onClick={()=>add(selected,quantity)}>{t('Aggiungi alla borsa','Add to bag')}<ShoppingBag size={18}/></button><small className="demo-prices">{t('Demo: prezzo indicativo, acquisto non attivo.','Demo: illustrative price, purchasing is not active.')}</small></div></>}</DialogContent></Dialog>
  <Sheet open={cartOpen} onOpenChange={setCartOpen}><SheetContent className="cart-sheet"><SheetTitle className="cart-heading">{t('La tua','Your')} <em>{t('borsa.','bag.')}</em></SheetTitle><SheetDescription>{count} {t('prodotti selezionati','selected items')}</SheetDescription><div className="cart-list">{cart.length===0?<div className="empty-cart"><ShoppingBag size={42}/><h3>{t('Un po’ di Sicilia ti aspetta.','A little Sicily is waiting.')}</h3><button className="pill-button dark" onClick={()=>{setCartOpen(false);document.getElementById('products')?.scrollIntoView({behavior:'smooth'});}}>{t('Esplora la dispensa','Explore the pantry')}</button></div>:cart.map(({product:p,qty})=><div className="cart-item" key={p.id}><Image unoptimized src={imagePath(p.image)} alt={en?p.nameEn:p.name} width={90} height={90}/><div><strong>{en?p.nameEn:p.name}</strong><small>{p.format}</small><div className="quantity small"><button onClick={()=>changeQty(p.id,-1)} aria-label={t('Riduci quantità','Decrease quantity')}><Minus size={14}/></button><span>{qty}</span><button onClick={()=>changeQty(p.id,1)} aria-label={t('Aumenta quantità','Increase quantity')}><Plus size={14}/></button></div></div><span>{money(p.price*qty,lang)}</span></div>)}</div>{cart.length>0&&<div className="cart-summary"><div><span>{t('Subtotale','Subtotal')}</span><strong>{money(total,lang)}</strong></div><p>{t('Spedizione UPS da calcolare nella versione completa.','UPS shipping to be calculated in the full version.')}</p><button className="pill-button dark" onClick={()=>setCheckout(true)}>{t('Riepilogo demo','Demo summary')}<ArrowRight size={18}/></button>{checkout&&<p className="demo-notice" role="status">{t('Questa è un’anteprima: nessun ordine viene inviato e nessun pagamento viene richiesto.','This is a preview: no order is submitted and no payment is requested.')}</p>}</div>}</SheetContent></Sheet>
  <Sheet open={menu} onOpenChange={setMenu}><SheetContent className="menu-sheet"><SheetTitle>Tenute Santangelo</SheetTitle><SheetDescription>Sicilia</SheetDescription>{[['#products',t('La nostra dispensa','Our pantry')],['#oil',t('L’olio','Olive oil')],['#land',t('La tenuta','Our land')]].map(([href,label])=><a href={href} key={href} onClick={()=>setMenu(false)}>{label}<ArrowUpRight/></a>)}<a href={sitePath('/admin/')}>Admin demo<ArrowUpRight/></a></SheetContent></Sheet>
 </div>;
}
