export type Product = {id:string;name:string;nameEn:string;category:string;format:string;price:number;image:string;description:string;descriptionEn:string;status:'Attivo'|'Bozza';stock:number;variants?:{label:string;price:number;stock:number}[];};
export const imagePath=(name:string)=>`${process.env.NEXT_PUBLIC_BASE_PATH || ''}/images/${name}`;
export const sitePath=(path:string)=>`${process.env.NEXT_PUBLIC_BASE_PATH || ''}${path}`;
export const logo='logo-tenute-santangelo-sicilia-147572.jpg';
export const categories=['Olio EVO','Oli aromatizzati','Agrumi','Specialità'];
export const initialProducts:Product[]=[
 {id:'TS-001',name:'Olio extravergine di oliva',nameEn:'Extra virgin olive oil',category:'Olio EVO',format:'5 L',price:60,image:'olio-extravergine-confezione-5l-147563.jpg',description:'Il carattere della nostra terra, in una confezione da cinque litri da tenere in dispensa.',descriptionEn:'The character of our land, in a five-litre pack for your pantry.',status:'Attivo',stock:24},
 {id:'TS-002',name:'Tris agli agrumi',nameEn:'Citrus oil trio',category:'Oli aromatizzati',format:'3 bottiglie',price:11,image:'tris-condimenti-arancio-limone-mandarino-147569.jpg',description:'Arancio, limone e mandarino. Tre condimenti a base di olio extravergine per dare un accento siciliano ai tuoi piatti.',descriptionEn:'Orange, lemon and mandarin. Three extra virgin olive oil condiments to bring a Sicilian touch to your table.',status:'Attivo',stock:38},
 {id:'TS-003',name:'Cedri di Sicilia',nameEn:'Sicilian citrons',category:'Agrumi',format:'Cassetta',price:25,image:'cedro-intero-e-tagliato-147570.jpg',description:'Buccia profumata e albedo generoso. Un agrume tutto da scoprire, dalle insalate alle ricette della tradizione.',descriptionEn:'A fragrant peel and generous pith. Discover this citrus fruit in salads and traditional recipes.',status:'Attivo',stock:16},
 {id:'TS-004',name:'Origano di Sicilia',nameEn:'Sicilian oregano',category:'Specialità',format:'25 g',price:2.2,image:'origano-sicilia-25g-147565.jpg',description:'Origano in mazzetti: il profumo semplice della cucina mediterranea.',descriptionEn:'Dried oregano bunches: the simple fragrance of Mediterranean cooking.',status:'Attivo',stock:60},
 {id:'TS-005',name:'Olive Nocellara del Belice',nameEn:'Nocellara del Belice olives',category:'Specialità',format:'1 kg sgocciolato',price:12,image:'olive-verdi-incise-nocellara-del-belice-147567.jpg',description:'Olive siciliane da tavola verdi incise. Confezione da 2 kg, peso sgocciolato 1 kg.',descriptionEn:'Sicilian scored green table olives. 2 kg pack, 1 kg drained weight.',status:'Attivo',stock:18},
 {id:'TS-006',name:'Pesto al finocchietto selvatico',nameEn:'Wild fennel pesto',category:'Specialità',format:'130 g',price:4.9,image:'pesto-finocchietto-selvatico-130g-147566.jpg',description:'Una specialità siciliana al finocchietto selvatico, da portare in tavola con la tua pasta preferita.',descriptionEn:'A Sicilian wild fennel speciality, to serve with your favourite pasta.',status:'Attivo',stock:32},
 {id:'TS-007',name:'Salsa di pomodoro datterino',nameEn:'Datterino tomato sauce',category:'Specialità',format:'330 g',price:3.9,image:'salsa-pomodoro-datterino-330g-147568.jpg',description:'Salsa pronta con pomodoro datterino. La semplicità trova posto a tavola.',descriptionEn:'Ready-to-use datterino tomato sauce. A place for simplicity at your table.',status:'Attivo',stock:45},
 {id:'TS-008',name:'Condimento all’arancio',nameEn:'Orange olive oil condiment',category:'Oli aromatizzati',format:'Bottiglia',price:3.8,image:'condimento-olio-evo-arancio-147564.jpg',description:'Condimento a base di olio extravergine di oliva all’arancio.',descriptionEn:'Orange-flavoured extra virgin olive oil condiment.',status:'Attivo',stock:28}
];
export const money=(value:number,lang='it')=>new Intl.NumberFormat(lang==='it'?'it-IT':'en-IE',{style:'currency',currency:'EUR'}).format(value);
